language: ruby

cache:
  directories:
    - bundle

before_install:
  - gem update --system
  - gem install bundler

rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6

addons:
  sonarcloud:
    organization: "kyaak-github"
    token:


script:
  - bundle exec rake spec
  - sonar-scanner

deploy:
  provider: rubygems
  api_key:

  gem: danger-code_coverage
  on:
    branch: master
    rvm: 2.6
